// Plan §1.5/§7: `llms.txt` (llmstxt.org convention) -- H1 (repo name) -> blockquote one-line
// summary -> H2-headed section of bullet-point links. **One deliberate reading choice** (plan
// §1.5): the convention as popularly documented targets a hosted website (URLs resolving over
// HTTP); Chart Room manages a local git repo's markdown docs, so this emits repo-relative markdown
// paths as the link targets instead of public URLs -- the pragmatic local-repo reading of the same
// convention. Only `llms.txt` (index) is built, not a companion `llms-full.txt` (plan §1.5/§12
// item 10: the spec's own "bonus... for free" framing covers the index only).

import { basename } from 'node:path';
import type { ChartRoomIndex, DocEntry } from './index-schema.js';

interface LlmsTxtEntry {
  title: string;
  path: string;
  /** first heading beyond the title, if any -- used as the bullet's short description (plan
   * §1.5's `- [Title](URL): short description` shape). */
  description?: string;
}

/** Defensive-only fallback: real `index.docs`/`unidentified` entries always carry a non-empty
 * `title` (the indexer itself already falls back to the filename stem at build time, `indexer.ts`
 * `titleFor`) -- this mirrors that same fallback for a hand-built fixture that deliberately omits
 * one, not new title-derivation logic (plan §8.1's `llms-txt.test.ts` case). */
function titleOrFilenameStem(doc: DocEntry): string {
  if (doc.title && doc.title.trim().length > 0) return doc.title;
  return basename(doc.path, '.md');
}

function toEntry(doc: DocEntry): LlmsTxtEntry {
  const title = titleOrFilenameStem(doc);
  // headings[0] is typically the doc's own H1 (same text as its title in the common case) --
  // the first heading *beyond* that is a more useful one-line description than repeating the title.
  const description = doc.headings.find((h) => h !== title);
  return description ? { title, path: doc.path, description } : { title, path: doc.path };
}

function formatBullet(entry: LlmsTxtEntry): string {
  const link = `- [${entry.title}](${entry.path})`;
  return entry.description ? `${link}: ${entry.description}` : link;
}

/**
 * Pure function (plan §2/§7): a fixture index -> the full `llms.txt` text. Includes every doc the
 * index knows about -- both id-keyed (`index.docs`) and id-less (`index.unidentified`) -- sorted by
 * path for deterministic output, since `llms.txt` is a link-based index, not an id-based one (plan
 * §1.5's own local-repo-relative reading applies uniformly to both).
 */
export function buildLlmsTxt(repoRoot: string, index: ChartRoomIndex, repoName?: string): string {
  const name = repoName ?? basename(repoRoot);
  const docs = [...Object.values(index.docs), ...index.unidentified]
    .slice()
    .sort((a, b) => a.path.localeCompare(b.path));

  const lines: string[] = [];
  lines.push(`# ${name}`);
  lines.push('');
  lines.push(`> Chart-Room-managed markdown docs for ${name}. Generated by \`chartroom llms-txt\`.`);
  lines.push('');
  lines.push('## Docs');
  lines.push('');
  if (docs.length === 0) {
    lines.push('(no docs found)');
  } else {
    for (const doc of docs) {
      lines.push(formatBullet(toEntry(doc)));
    }
  }
  lines.push('');
  return lines.join('\n');
}
