import { describe, expect, it } from 'vitest';
import { emptyIndex, type ChartRoomIndex } from '../src/index-schema.js';
import { buildLlmsTxt } from '../src/llms-txt.js';

function buildIndex(overrides: Partial<ChartRoomIndex> = {}): ChartRoomIndex {
  return { ...emptyIndex(), ...overrides };
}

describe('buildLlmsTxt', () => {
  it('emits the H1/blockquote/H2/bullet-per-doc shape, sorted by path, with a heading-derived description', () => {
    const index = buildIndex({
      docs: {
        b: { path: 'b/doc.md', title: 'B Doc', headings: ['B Doc', 'Overview'], outbound: [] },
        a: { path: 'a/doc.md', title: 'A Doc', headings: ['A Doc'], outbound: [] },
      },
    });

    const content = buildLlmsTxt('/repo', index, 'my-repo');

    expect(content).toBe(
      [
        '# my-repo',
        '',
        '> Chart-Room-managed markdown docs for my-repo. Generated by `chartroom llms-txt`.',
        '',
        '## Docs',
        '',
        '- [A Doc](a/doc.md)',
        '- [B Doc](b/doc.md): Overview',
        '',
      ].join('\n'),
    );
  });

  it('includes unidentified (id-less) docs alongside id-keyed ones', () => {
    const index = buildIndex({
      docs: { a: { path: 'a.md', title: 'A', headings: ['A'], outbound: [] } },
      unidentified: [{ path: 'z-no-id.md', title: 'No Id Doc', headings: ['No Id Doc'], outbound: [] }],
    });
    const content = buildLlmsTxt('/repo', index, 'repo');
    expect(content).toContain('- [A](a.md)');
    expect(content).toContain('- [No Id Doc](z-no-id.md)');
  });

  it('falls back to the filename stem when a fixture omits a title (same fallback the indexer itself already applies at build time)', () => {
    const index = buildIndex({
      docs: { x: { path: 'sub/untitled-thing.md', title: '', headings: [], outbound: [] } },
    });
    const content = buildLlmsTxt('/repo', index, 'repo');
    expect(content).toContain('- [untitled-thing](sub/untitled-thing.md)');
  });

  it('defaults the repo name to the repoRoot basename when none is given', () => {
    const content = buildLlmsTxt('/some/path/my-repo', buildIndex());
    expect(content.split('\n')[0]).toBe('# my-repo');
  });

  it('prints a placeholder line for an empty index rather than an empty Docs section', () => {
    const content = buildLlmsTxt('/repo', buildIndex(), 'repo');
    expect(content).toContain('(no docs found)');
  });
});
